# demo/99-setup-microk8s-gitea.yml
---
- hosts: n1
  gather_facts: "no"

  vars_files:
    - ../vars/vault.yml

  tasks:
    - name: "add gitea-charts helm repo"
      command: /snap/bin/helm repo add gitea-charts https://dl.gitea.com/charts/
      changed_when: false

    - name: "upload values-gitea.yaml into /root"
      copy:
        src: ../files/demo/values-gitea.yaml
        dest: /root/values-gitea.yaml
        owner: root
        group: root
        mode: "0644"

    - name: "install gitea helm chart"
      command: >
        /snap/bin/helm upgrade --install gitea gitea-charts/gitea
        -f /root/values-gitea.yaml
        --set gitea.admin.username={{ gitea_admin_username }}
        --set gitea.admin.password={{ gitea_admin_password }}
        --set postgresql.global.postgresql.auth.password={{ gitea_db_password }}
        --set valkey.auth.password={{ gitea_valkey_password }}
        --namespace default
