# 03-setup-microk8s-cluster.yml
---
- hosts: n1
  gather_facts: "no"

  tasks:

      - name: "generate join command for n2"
        shell: /snap/bin/microk8s add-node | grep 10.0.0.2 | head -1
        register: k8s_join_cmd_n2
        changed_when: false

      - name: "generate join command for n3"
        shell: /snap/bin/microk8s add-node | grep 10.0.0.2 | head -1
        register: k8s_join_cmd_n3
        changed_when: false

      - name: "store join commands in dummy host"
        add_host:
            name: "K8S_TOKEN_HOLDER"
            join_cmd_n2: "{{ k8s_join_cmd_n2.stdout }}"
            join_cmd_n3: "{{ k8s_join_cmd_n3.stdout }}"

- hosts: n2
  gather_facts: "no"

  tasks:

      - name: "check if n2 already in cluster"
        shell: /snap/bin/microk8s status | grep -c "n2"
        register: n2_joined
        failed_when: false
        changed_when: false

      - name: "join node n2"
        shell: "{{ hostvars['K8S_TOKEN_HOLDER']['join_cmd_n2'] }}"
        when:
            - hostvars['K8S_TOKEN_HOLDER']['join_cmd_n2'] != ""
            - n2_joined.stdout == "0"

- hosts: n3
  gather_facts: "no"

  tasks:

      - name: "check if n3 already in cluster"
        shell: /snap/bin/microk8s status | grep -c "n3"
        register: n3_joined
        failed_when: false
        changed_when: false

      - name: "join node n3"
        shell: "{{ hostvars['K8S_TOKEN_HOLDER']['join_cmd_n3'] }}"
        when:
            - hostvars['K8S_TOKEN_HOLDER']['join_cmd_n3'] != ""
            - n3_joined.stdout == "0"
