# 05-setup-microk8s-ingress-nginx.yml
---
- hosts: n1
  gather_facts: "no"

  tasks:

      # helm repo command is idempotent
      - name: "add ingress-nginx helm repo"
        command: >
            /snap/bin/helm repo add
            ingress-nginx https://kubernetes.github.io/ingress-nginx
        changed_when: false

      - name: "check for ingress-nginx helm release"
        command: /snap/bin/helm status ingress-nginx
        register: ingress_status
        failed_when: false
        changed_when: false
        ignore_errors: "true"

      - name: "install ingress-nginx helm chart"
        command: >
            /snap/bin/helm install ingress-nginx ingress-nginx/ingress-nginx
        when: ingress_status.rc != 0
