---
- hosts: all
  gather_facts: "no"

  tasks:
      - name: run "apt-get update"
        apt:
            update_cache: "yes"

      - name: update all packages to the latest
        apt:
            upgrade: dist

      - name: install "snapd" package
        apt:
            package: snapd
            state: present

      - name: install "microk8s" snap with option --classic
        snap:
            name: microk8s
            classic: "yes"
            state: present
        notify:
            - enable snapd
            - restart snapd
            - enable microk8s
            - reboot

  handlers:
      - name: enable snapd
        service:
            name: snapd
            enabled: "yes"
      - name: restart snapd
        service:
            name: snapd
            state: restarted
      - name: enable microk8s
        command: /snap/bin/microk8s.enable dns storage ingress helm3
      - name: reboot
        reboot:
            reboot_timeout: 120

- hosts: m1
  gather_facts: "no"

  tasks:

      - name: create aliases
        template:
            src: templates/bash_aliases.j2
            dest: /root/.bash_aliases
            owner: root
            group: root
            mode: '0600'

      - name: add floating ip
        template:
            src: templates/60-floating-ip.yaml.j2
            dest: /etc/netplan/60-floating-ip.yaml
            owner: root
            group: root
            mode: '0644'
        notify:
            - netplan apply

  handlers:
      - name: netplan apply
        command: netplan apply
